'use strict';
const $=id=>document.getElementById(id);
const channels=[
{id:'linkedin',name:'LinkedIn profile',short:'in · Profile',icon:'in',author:'Barbara Arnold',limit:3000,note:'Personal profile preview. Live publishing will require a separate account connection.'},
{id:'company',name:'LinkedIn company',short:'in · Company',icon:'in',author:'Barb Arnold Creative',limit:3000,note:'Company Page preview. Live access will require Page permissions.'},
{id:'facebook',name:'Facebook',short:'f · Facebook',icon:'f',author:'Barb Arnold Creative',limit:63206,note:'Business Page preview. No Facebook account is connected.'},
{id:'instagram',name:'Instagram',short:'◎ · Instagram',icon:'◎',author:'Barb Arnold Creative',limit:2200,note:'Manual posting: download your image and copy the caption. Direct publishing requires a professional Instagram account.'},
{id:'threads',name:'Threads',short:'@ · Threads',icon:'@',author:'Barb Arnold Creative',limit:500,note:'Standard Threads post preview. Threads needs its own publishing authorization.'}
];
const examples={
resume:['Your résumé should do more than list what you were responsible for. It should show the difference you made.','Start with one bullet. Ask yourself: What changed because of my work? Who benefited? What evidence can I share?','Replace a task list with a clear story of your contribution. Use real details, and only include numbers you can support.'],
linkedin:['Does your LinkedIn headline describe your job title—or the value you bring?','Try this framework: what you do + who you help + the expertise that makes your work valuable.','Your profile should sound like you, with a clear direction for where you want to go next.'],
interview:['A strong interview answer starts before the interview.','Choose three real examples: a problem you solved, a change you navigated, and a time you worked through a challenge with others.','Practice explaining the situation, your specific contribution, and the result. Clear beats memorized.'],
transition:['Changing careers does not mean starting your story from scratch.','Look for the thread between your experience and the work you want next. Problem-solving, communication, leadership, and technical judgment can travel with you.','Make that connection explicit. Help a hiring manager understand how your experience meets their needs.'],
leadership:['Clear leadership communication starts with the questions your audience is already asking.','What is changing? Why does it matter? What happens next? What do I need to do?','Before adding more information, make sure those four answers are easy to find.']
};
const questions={resume:'What is the hardest part of describing your accomplishments?',linkedin:'When did you last revisit your LinkedIn headline?',interview:'Which interview question would you most like to feel ready for?',transition:'What strength would you bring into your next chapter?',leadership:'What makes a message from a leader useful to you?'};
const key='bac-social-studio-v1'; let posts=[];
try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(data))posts=data.filter(p=>p&&typeof p.id==='string'&&typeof p.text==='string'&&Array.isArray(p.selected));}catch(e){setTimeout(()=>toast('Saved drafts could not be read. You can still create a new draft.'),100)}
let active='linkedin',selected=['linkedin','company','facebook'],variants={},imageData='',sourceImage=null,editId=null,month=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4500)}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function view(id){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('nav button').forEach(e=>e.classList.toggle('active',e.dataset.view===id));$('crumb').textContent={compose:'Create a post',library:'Drafts & calendar',analytics:'Analytics',accounts:'Accounts'}[id];if(id==='library')renderLibrary();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));
function renderDestinations(){
$('destinations').innerHTML=channels.map(c=>'<label class="destination"><input type="checkbox" value="'+c.id+'" '+(selected.includes(c.id)?'checked':'')+'>'+c.short+'</label>').join('');
$('destinations').querySelectorAll('input').forEach(e=>e.onchange=()=>{selected=e.checked?[...selected,e.value]:selected.filter(v=>v!==e.value);renderPreview()});
}
function textFor(id){return Object.hasOwn(variants,id)?variants[id]:$('copy').value}
function renderPreview(){
$('preview-tabs').innerHTML=channels.map(c=>'<button class="'+(c.id===active?'active':'')+'" data-channel="'+c.id+'" aria-pressed="'+(c.id===active)+'">'+c.short+'</button>').join('');
$('preview-tabs').querySelectorAll('button').forEach(e=>e.onclick=()=>{active=e.dataset.channel;renderPreview()});
const c=channels.find(c=>c.id===active),text=textFor(active),length=Array.from(text).length;
$('preview-author').textContent=c.author;$('preview-meta').textContent=c.name+' · '+(selected.includes(active)?'Selected destination':'Not selected');
$('network-icon').textContent=c.icon;$('preview-text').textContent=text||'Your post preview will appear here.';
$('channel-copy').value=text;$('char-count').textContent=Array.from($('copy').value).length+' characters';
$('channel-count').textContent=length.toLocaleString()+' / '+c.limit.toLocaleString();$('channel-count').classList.toggle('error-text',length>c.limit);
$('channel-note').textContent=(length>c.limit?'This message is over the demo limit. Shorten it before simulating publishing. ': '')+c.note;
$('channel-note').classList.toggle('warning',c.id==='instagram'||length>c.limit);
$('preview-image').hidden=!imageData;if(imageData)$('preview-image').src=imageData;else $('preview-image').removeAttribute('src');
$('remove-image').hidden=!imageData;$('download-image').disabled=!imageData;
}
$('copy').oninput=renderPreview;$('channel-copy').oninput=()=>{const start=$('channel-copy').selectionStart,end=$('channel-copy').selectionEnd;variants[active]=$('channel-copy').value;renderPreview();$('channel-copy').setSelectionRange(start,end)};
$('reset-channel').onclick=()=>{delete variants[active];renderPreview()};
function hasContent(){return !!$('copy').value.trim()||Object.values(variants).some(v=>v.trim())||!!imageData}
function newPost(){if(hasContent()&&!confirm('Start a new post? Any unsaved changes will be cleared.'))return;$('copy').value='';variants={};imageData='';sourceImage=null;editId=null;$('edit-status').textContent='New draft';renderPreview()}
$('new-post').onclick=newPost;
$('sample').onclick=()=>{if(hasContent()&&!confirm('Replace the current text with a sample? Your image will stay.'))return;const t=$('topic').value,parts=examples[t];$('copy').value=($('tone').value==='question'?[questions[t],parts[1],parts[2]]:parts).join('\n\n')+'\n\nReady for a clearer career story? Explore support at barbarnoldcreative.com.';variants={threads:parts[0]+'\n\n'+questions[t]};renderPreview();toast('Sample loaded. Edit it to make it your own.')};
function size(){return {square:[1080,1080],portrait:[1080,1350],landscape:[1200,628]}[$('format').value]}
function canvas(){const c=document.createElement('canvas');[c.width,c.height]=size();return c}
function wrap(ctx,text,x,y,maxWidth,lineHeight,maxLines){const words=text.split(/\s+/);let line='',count=0;for(let i=0;i<words.length;i++){const test=line+words[i]+' ';if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line.trim(),x,y);line=words[i]+' ';y+=lineHeight;count++;if(count===maxLines-1){let rest=[line,...words.slice(i+1)].join(' ');while(ctx.measureText(rest).width>maxWidth&&rest.length)rest=rest.slice(0,-1);ctx.fillText(rest.trim()+'…',x,y);return}}else line=test}ctx.fillText(line.trim(),x,y)}
function drawTip(){const c=canvas(),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.fillStyle='#dfecea';ctx.fillRect(0,0,w,h);ctx.fillStyle='#333a4e';ctx.fillRect(65,70,65,5);ctx.font='22px Arial';ctx.fillText('BARB ARNOLD CREATIVE',65,130);ctx.font=(h<800?'52':'62')+'px Georgia';wrap(ctx,($('copy').value.trim().split('\n')[0]||'Your experience deserves a clearer story.').slice(0,240),65,h<800?240:310,w-140,h<800?68:83,h<800?3:6);ctx.font='22px Arial';ctx.fillText('CAREER CLARITY. CONFIDENT COMMUNICATION.',65,h-100);ctx.font='20px Arial';ctx.fillText('barbarnoldcreative.com',65,h-60);imageData=c.toDataURL('image/png');renderPreview()}
$('tip-card').onclick=()=>{sourceImage='tip';drawTip();toast('Tip card created from your opening line.')};
async function redrawImage(){if(sourceImage==='tip'){drawTip();return}if(!sourceImage)return;const img=new Image();img.onload=()=>{const c=canvas(),ctx=c.getContext('2d');ctx.fillStyle='#edf3f1';ctx.fillRect(0,0,c.width,c.height);const scale=($('fit').value==='cover'?Math.max:Math.min)(c.width/img.width,c.height/img.height);ctx.drawImage(img,(c.width-img.width*scale)/2,(c.height-img.height*scale)/2,img.width*scale,img.height*scale);imageData=c.toDataURL('image/jpeg',.86);renderPreview()};img.onerror=()=>toast('That image could not be opened. Try a JPG, PNG, or WebP.');img.src=sourceImage}
$('upload').onchange=e=>{const file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024){toast('Choose a JPG, PNG, or WebP smaller than 15 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{sourceImage=reader.result;redrawImage()};reader.onerror=()=>toast('Could not read the image.');reader.readAsDataURL(file);e.target.value=''};
$('format').onchange=redrawImage;$('fit').onchange=redrawImage;
$('remove-image').onclick=()=>{imageData='';sourceImage=null;renderPreview()};
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click()}
$('download-image').onclick=()=>download(imageData,'bac-social-'+$('format').value+(imageData.startsWith('data:image/png')?'.png':'.jpg'));
function persist(next){try{localStorage.setItem(key,JSON.stringify(next));posts=next;$('post-count').textContent=posts.length;return true}catch(e){toast('Browser storage is full or unavailable. Download your image or export drafts before trying again.');return false}}
function validate(publish=false){if(!selected.length){toast('Select at least one destination.');return false}if(!hasContent()){toast('Add a message or image first.');return false}if(publish){const invalid=channels.filter(c=>selected.includes(c.id)&&(!textFor(c.id).trim()&&!imageData||Array.from(textFor(c.id)).length>c.limit));if(invalid.length){toast('Check the message for '+invalid.map(c=>c.name).join(', ')+'.');return false}if(selected.includes('instagram')&&!imageData){toast('Instagram needs an image. Upload one or make a tip card.');return false}}return true}
function save(status='draft',date=''){if(!validate(status!=='draft'))return false;const p={id:editId||crypto.randomUUID(),text:$('copy').value,variants:{...variants},selected:[...selected],image:imageData,format:$('format').value,fit:$('fit').value,status,date,updated:new Date().toISOString()};const next=posts.filter(x=>x.id!==p.id);next.unshift(p);if(!persist(next))return false;editId=p.id;$('edit-status').textContent='Saved in this browser';return true}
$('save').onclick=()=>{if(save())toast('Draft saved in this browser.')};
$('schedule-open').onclick=()=>{if(!validate(true))return;const t=new Date(Date.now()+3600000);t.setMinutes(t.getMinutes()-t.getTimezoneOffset());$('schedule-time').value=t.toISOString().slice(0,16);$('timezone').textContent='Time zone: '+Intl.DateTimeFormat().resolvedOptions().timeZone;$('schedule-dialog').showModal()};
$('schedule-cancel').onclick=()=>$('schedule-dialog').close();
$('schedule-form').onsubmit=e=>{e.preventDefault();const date=new Date($('schedule-time').value);if(!Number.isFinite(date.getTime())||date<=new Date()){toast('Choose a future date and time.');return}if(save('scheduled',date.toISOString())){$('schedule-dialog').close();toast('Added to the demo calendar. No automatic publishing.');view('library')}};
$('publish').onclick=()=>{if(!save('simulated'))return;$('result-title').textContent='Publishing simulation complete';$('result-body').innerHTML='<p>No content was sent to any social platform.</p>'+channels.filter(c=>selected.includes(c.id)).map(c=>'<p><strong>'+c.name+'</strong><br><span class="small">'+(c.id==='instagram'?'Manual posting needed. Download the image and copy your caption.':'Demo successful · No live connection')+'</span></p>').join('');$('results-dialog').showModal()};
$('results-close').onclick=()=>$('results-dialog').close();
function loadPost(id){const p=posts.find(p=>p.id===id);if(!p)return;if(hasContent()&&editId!==id&&!confirm('Open this saved post? Unsaved composer changes will be cleared.'))return;editId=p.id;$('copy').value=p.text;variants={...(p.variants||{})};selected=[...p.selected];imageData=p.image||'';sourceImage=imageData||null;$('format').value=p.format||'square';$('fit').value=p.fit||'contain';$('edit-status').textContent='Editing saved post';renderDestinations();renderPreview();view('compose')}
function renderLibrary(){
const year=month.getFullYear(),m=month.getMonth(),today=new Date();$('month-title').textContent=month.toLocaleDateString(undefined,{month:'long',year:'numeric'});let html=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>'<div class="day-label">'+d+'</div>').join('');for(let i=0;i<month.getDay();i++)html+='<div class="day"></div>';for(let day=1;day<=new Date(year,m+1,0).getDate();day++){const matches=posts.filter(p=>{const d=new Date(p.date);return p.status==='scheduled'&&d.getFullYear()===year&&d.getMonth()===m&&d.getDate()===day});html+='<div class="day '+(today.getFullYear()===year&&today.getMonth()===m&&today.getDate()===day?'today':'')+'">'+day+(matches.length?'<span>'+matches.length+' demo scheduled</span>':'')+'</div>'}$('calendar').innerHTML=html;
const visible=posts.filter(p=>$('filter').value==='all'||p.status===$('filter').value);
$('posts').innerHTML=visible.length?visible.map(p=>'<article class="panel post-row"><div><span class="tag">'+({draft:'Draft',scheduled:'Demo scheduled',simulated:'Demo published'}[p.status]||'Draft')+'</span><p>'+escapeHTML(p.text.slice(0,240)||'(Image post)')+'</p><small>'+p.selected.map(id=>escapeHTML(channels.find(c=>c.id===id)?.name||id)).join(' · ')+'</small>'+(p.date?'<div class="small">'+escapeHTML(new Date(p.date).toLocaleString())+'</div>':'')+'</div><div class="button-row"><button class="secondary" data-edit="'+p.id+'">Edit</button><button class="text-button danger" data-delete="'+p.id+'">Delete</button></div></article>').join(''):'<div class="panel empty"><h2>A little planning goes a long way.</h2><p>No posts here yet. Save a draft or schedule a demo post to get started.</p></div>';
$('posts').querySelectorAll('[data-edit]').forEach(e=>e.onclick=()=>loadPost(e.dataset.edit));$('posts').querySelectorAll('[data-delete]').forEach(e=>e.onclick=()=>{if(confirm('Delete this saved post?')){if(persist(posts.filter(p=>p.id!==e.dataset.delete))){if(editId===e.dataset.delete){editId=null;$('edit-status').textContent='Unsaved post'}renderLibrary()}}});
}
$('prev-month').onclick=()=>{month.setMonth(month.getMonth()-1);renderLibrary()};$('next-month').onclick=()=>{month.setMonth(month.getMonth()+1);renderLibrary()};$('filter').onchange=renderLibrary;
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,exported:new Date().toISOString(),posts},null,2)],{type:'application/json'}));download(url,'bac-social-drafts.json');setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Draft export downloaded.')};
$('bars').innerHTML=[['LinkedIn profile',5120],['LinkedIn company',2680],['Facebook',2140],['Instagram',1520],['Threads',1020]].map(([name,num])=>'<div class="bar-row"><span>'+name+'</span><div class="bar-track"><div class="bar-fill" style="width:'+num/5120*100+'%"></div></div><strong>'+num.toLocaleString()+'</strong></div>').join('');
$('account-cards').innerHTML=channels.map(c=>'<article class="panel"><div class="account-top"><div class="avatar">'+c.icon+'</div><div><h2>'+c.name+'</h2><span class="tag">'+(c.id==='instagram'?'Manual posting':'Not connected')+'</span></div></div><p>'+c.note+'</p><button class="secondary" data-account="'+c.id+'">'+(c.id==='instagram'?'View posting options':'Preview connection')+'</button></article>').join('');
$('account-cards').querySelectorAll('button').forEach(e=>e.onclick=()=>{const c=channels.find(c=>c.id===e.dataset.account);$('result-title').textContent=c.name;$('result-body').textContent=c.id==='instagram'?'Keep your personal account and post manually using the prepared image and caption. A future live integration requires switching to a Business or Creator account.':'In the live version, this button will open '+c.name+' authorization. You will choose the account or Page and approve publishing permissions. This mockup does not collect passwords or connect accounts.';$('results-dialog').showModal()});
$('copy').value=examples.resume.join('\n\n');variants.threads=examples.resume[0]+'\n\n'+questions.resume;
$('post-count').textContent=posts.length;renderDestinations();renderPreview();
